blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import ArticleListView, ArticleDetailView, ArticleCreateView, ArticleUpdateView, ArticleDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('articles/', ArticleListView.as_view(), name='articles'),
    path('articles/create/', ArticleCreateView.as_view(), name='article_create'),
    path('articles/<slug:slug>/', ArticleDetailView.as_view(), name='article_detail'),
    path('articles/<slug:slug>/edit', ArticleUpdateView.as_view(), name='article_update'),
    path('articles/<slug:slug>/delete', ArticleDeleteView.as_view(), name='article_delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('', include('blog.urls', namespace='blog')),
    path("users/", include("users.urls", namespace="users")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

NULLABLE = {"blank": True, "null": True}


class Article(models.Model):
    """
    Класс Статьи (Поста)
    """

    title = models.CharField(max_length=150, verbose_name="заголовок")
    slug = models.CharField(max_length=150, verbose_name="slug", **NULLABLE)
    body = models.TextField(verbose_name='содержимое')
    preview = models.ImageField(upload_to="blog/preview", verbose_name="изображение", **NULLABLE)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="дата создания")
    is_published = models.BooleanField(default=False, verbose_name='опубликовано')
    view_count = models.PositiveIntegerField(default=0, verbose_name='количество просмотров')

    class Meta:
        verbose_name = "статья"
        verbose_name_plural = "статьи"
        ordering = (
            "-created_at",
        )

    def __str__(self):
        return f"{self.title}"

blog/forms.py
from django import forms

from blog.models import Article


class ArticleForm(forms.ModelForm):

    class Meta:
        model = Article
        fields = ('title', 'body', 'preview', 'is_published')

blog/views.py
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from pytils.translit import slugify
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin

from blog.forms import ArticleForm
from blog.models import Article


class ArticleListView(ListView):
    extra_context = {
        'title': 'Новости',
    }
    model = Article
    paginate_by = 4
    context_object_name = "article_list"

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        user = self.request.user

        # Контент-менеджер может видеть все статьи
        if user.has_perm('blog.add_article') and user.has_perm('blog.change_article'):
            return queryset

        # Обычный пользователь видит только опубликованные статьи
        return queryset.filter(is_published=True)


class ArticleDetailView(DetailView):
    model = Article
    context_object_name = "article"

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.view_count += 1
        self.object.save()
        return self.object


class ArticleCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Article
    form_class = ArticleForm
    permission_required = ['blog.add_article']

    def form_valid(self, form):
        new_article = form.save(commit=False)
        new_article.slug = slugify(new_article.title)
        new_article.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog:article_detail', kwargs={'slug': self.object.slug})


class ArticleUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Article
    form_class = ArticleForm
    permission_required = ['blog.change_article']

    def form_valid(self, form):
        new_article = form.save(commit=False)
        new_article.slug = slugify(new_article.title)
        new_article.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog:article_detail', kwargs={'slug': self.object.slug})


class ArticleDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Article
    success_url = reverse_lazy('blog:articles')

    def test_func(self):
        return self.request.user.is_superuser

blog/templates/blog/article_confirm_delete.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="position-relative w-100 vh-100">
    <form method="post" class="position-absolute top-50 start-50 translate-middle ">
        {% csrf_token %}
        <p>Вы действительно хотите удалить статью <b>{{ object.title }}</b>?</p>
        <div class="btn-group justify-content-center w-100" role="group">
            <a href="{% url 'blog:article_detail' object.slug %}" class="btn btn-success">Отмена</a>
            <button class="btn btn-danger" type="submit">Удалить</button>
        </div>
    </form>
</div>
{% endblock %}

blog/templates/blog/article_detail.html
{% extends 'catalog/base.html' %}
{% load catalog_tags %}
{% block content %}
<div class="row">

    <h1 class="mb-4">{{ article.title }}</h1>

    {% if article.preview %}
    <div class="text-center mb-4">
        <img src="{{ article.preview | media_filter }}" alt="{{ article.title }}" class="img-fluid rounded">
    </div>
    {% endif %}

    <div class="mb-4">
        {{ article.body }}
    </div>

    <div class="d-flex justify-content-between text-muted">
        <small>Дата создания: {{ article.created_at|date:"d.m.Y" }}</small>
        <small>Количество просмотров: {{ article.view_count }}</small>
    </div>
</div>

<div class="mt-4 btn-group" role="group">
    {% if perms.blog.change_article %}
    <a href="{% url 'blog:article_update' object.slug %}" class="btn btn-primary m-1">Изменить статью</a>
    {% endif %}
    {% if user.is_superuser %}
    <a href="{% url 'blog:article_delete' object.slug %}" class="btn btn-danger m-1">Удалить статью</a>
    {% endif %}
</div>
{% if perms.blog.change_article %}
<div class="m-4 btn-group" role="group">
    {% if article.is_published %}
    <span class="badge bg-success">Опубликовано</span>
    {% else %}
    <span class="badge bg-danger">Не опубликовано</span>
    {% endif %}
</div>
{% endif %}
{% endblock %}

blog/templates/blog/article_form.html
{% extends 'catalog/base.html' %}
{% block content %}
{% load django_bootstrap5 %}
<div class="row d-flex justify-content-center">
    <div class="col-6">
        {% if object %}
            <h1 class="mt-1">Изменить статью</h1>
        {% else %}
            <h1 class="mt-1">Добавить статью</h1>
        {% endif %}
        <!-- Форма создания и редактирования статьи -->
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
            <button type="submit" class="btn btn-primary">
                {% if object %}
                    Сохранить изменения
                {% else %}
                    Добавить
                {% endif %}
            </button>
        </form>
    </div>
</div>
{% endblock %}

blog/templates/blog/article_list.html
{% extends 'catalog/base.html' %}
{% load catalog_tags %}
{% block content %}
{% if perms.blog.add_article %}
<div class="row">
    <div class="col-4 d-flex justify-content-center">
        <a class="p-2 btn btn-outline-primary mb-3" href="{% url 'blog:article_create' %}">Добавить статью</a>
    </div>
</div>
{% endif %}
<div class="row mb-2">
    {% for article in article_list %}
    <div class="col-md-6">
        <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
            <div class="col p-4 d-flex flex-column position-static">
                <h3 class="mb-0">{{ article.title }}</h3>
                <div class="mb-1 text-muted">{{ article.created_at | date:"d.m.Y"}}</div>
                <p class="card-text mb-auto">{{ article.body | truncatechars:250 }}</p>
                <a href="{% url 'blog:article_detail' article.slug %}" class="stretched-link">Продолжить чтение</a>
            </div>
            <div class="col-auto d-none d-lg-block">
                <img src="{{ article.preview | media_filter }}"
                     alt="Article">
            </div>

            {% if perms.blog.change_article %}
            <div class="m-4 btn-group" role="group">
                {% if article.is_published %}
                <span class="badge bg-success">Опубликовано</span>
                {% else %}
                <span class="badge bg-danger">Не опубликовано</span>
                {% endif %}
            </div>
            {% endif %}

        </div>
    </div>
    {% endfor %}
</div>
{% include "catalog/includes/paginator.html" %}
{% endblock %}