blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import ArticleListView, ArticleDetailView, ArticleCreateView, ArticleUpdateView, ArticleDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('articles/', ArticleListView.as_view(), name='articles'),
    path('articles/create/', ArticleCreateView.as_view(), name='article_create'),
    path('articles/<slug:slug>/', ArticleDetailView.as_view(), name='article_detail'),
    path('articles/<slug:slug>/edit', ArticleUpdateView.as_view(), name='article_update'),
    path('articles/<slug:slug>/delete', ArticleDeleteView.as_view(), name='article_delete'),
]

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from catalog.apps import CatalogConfig
from catalog.views import ContactView, ProductListView, ProductDetailView, ProductCreateView, ProductUpdateView, \
    ProductDeleteView, CategoryListView

app_name = CatalogConfig.name

urlpatterns = [
    path('', ProductListView.as_view(), name='product_list'),
    path('products/<int:pk>/', cache_page(60)(ProductDetailView.as_view()), name='product_detail'),
    path('products/create/', ProductCreateView.as_view(), name='create_product'),
    path('products/<int:pk>/edit', ProductUpdateView.as_view(), name='product_update'),
    path('products/<int:pk>/delete', ProductDeleteView.as_view(), name='product_delete'),
    path('categories/', CategoryListView.as_view(), name='category_list'),
    path('contacts/', ContactView.as_view(), name='contacts')
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('', include('blog.urls', namespace='blog')),
    path("users/", include("users.urls", namespace="users")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from users.apps import UsersConfig
from users.views import UserCreateView, email_verification, UserPasswordResetView, ProfileView, UserPasswordChangeView

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', UserCreateView.as_view(), name='register'),
    path('email-confirm/<str:token>/', email_verification, name='email-confirm'),
    path("password-reset/", UserPasswordResetView.as_view(), name='password_reset'),
    path("profile/", ProfileView.as_view(), name="profile"),
    path("password-change/", UserPasswordChangeView.as_view(), name='password_change'),
]

catalog/models.py
from django.db import models

from users.models import User

NULLABLE = {"blank": True, "null": True}


class Category(models.Model):
    """
    Класс категории товара
    """

    name = models.CharField(
        max_length=100,
        verbose_name="Наименование",
        help_text="Введите наименование категории",
    )

    description = models.TextField(
        verbose_name="Описание",
        help_text="Введите описание категории",
        **NULLABLE,
    )

    class Meta:
        verbose_name = "категория"
        verbose_name_plural = "категории"
        ordering = ("name",)

    def __str__(self):
        """
        Строковое категории
        """
        return f"{self.name}"


class Product(models.Model):
    """
    Класс товара
    """

    name = models.CharField(
        max_length=100,
        verbose_name="Товар",
        help_text="Введите наименование товара",
    )

    description = models.TextField(
        verbose_name="Описание",
        help_text="Введите описание товара",
        **NULLABLE,
    )

    preview = models.ImageField(
        upload_to="catalog/preview",
        verbose_name="Изображение",
        help_text="Загрузите изображение товара",
        **NULLABLE,
    )

    category = models.ForeignKey(
        "Category",
        on_delete=models.SET_NULL,
        verbose_name="Категория",
        help_text="Введите категорию товара",
        related_name="products",
        **NULLABLE,
    )

    price = models.DecimalField(
        max_digits=12,
        decimal_places=2,
        verbose_name="Цена",
        help_text="Введите цену",
        default=0.0,
    )

    owner = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        verbose_name="Владелец",
        help_text="Укажите владельца",
        **NULLABLE,
    )

    is_published = models.BooleanField(
        default=False,
        verbose_name="Опубликовано",
        help_text="Отметить для публикации"
    )

    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    updated_at = models.DateTimeField(
        auto_now=True, verbose_name="Дата последнего изменения"
    )

    class Meta:
        verbose_name = "товар"
        verbose_name_plural = "товары"
        ordering = (
            "name",
            "price",
            "created_at",
            "updated_at",
            "category",
        )
        permissions = [
            ('can_set_published', 'Can set published'),
            ('can_edit_product_description', 'Can edit description'),
            ('can_edit_category_product', 'Can edit category',),
        ]

    def __str__(self):
        return f"{self.name}"


class Contact(models.Model):
    name = models.CharField(max_length=100, verbose_name="Имя")
    phone = models.CharField(max_length=12, verbose_name="Телефон")
    address = models.CharField(max_length=255, verbose_name="Адрес", **NULLABLE)

    class Meta:
        verbose_name = "контакт"
        verbose_name_plural = "контакты"
        ordering = ("name",)

    def __str__(self):
        return self.name


class Version(models.Model):
    product = models.ForeignKey(
        Product,
        on_delete=models.SET_NULL,
        verbose_name="Продукт",
        **NULLABLE,
        related_name="version",
    )
    version_number = models.IntegerField(verbose_name="Номер версии")
    name = models.CharField(max_length=150, verbose_name="Название версии")
    is_current_version = models.BooleanField(
        default=False, verbose_name="Признак текущей версии"
    )

    class Meta:
        verbose_name = "Версия"
        verbose_name_plural = "Версии"
        ordering = (
            "product",
            "version_number",
            "name",
        )

    def __str__(self):
        return f"{self.name}"

catalog/forms.py
from django import forms
from .models import Product, Version


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        exclude = ("owner",)

    prohibited_words_list = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция',
                             'радар']

    def clean_name(self):
        cleaned_data = self.cleaned_data['name']

        for word in self.prohibited_words_list:
            if word in cleaned_data:
                raise forms.ValidationError('Запрещенные слова в названии!')

        return cleaned_data

    def clean_description(self):
        cleaned_data = self.cleaned_data['description']

        for word in self.prohibited_words_list:
            if word in cleaned_data:
                raise forms.ValidationError('Запрещенные слова в описании!')

        return cleaned_data


class ProductModeratorsForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = ('description', 'category', 'is_published',)


class VersionForm(forms.ModelForm):
    class Meta:
        model = Version
        fields = "__all__"


ProductFormset = forms.inlineformset_factory(
    Product,
    Version,
    form=VersionForm,
    extra=1)


class ProductVersionFormSet(ProductFormset):
    def clean(self):
        version_forms = self.forms
        is_latest_count = len([1 for f in version_forms if f.instance.is_current_version])
        if is_latest_count > 1:
            raise forms.ValidationError('Может быть только одна текущая версия продукта!')
        super().clean()

catalog/views.py
from django.urls import reverse_lazy, reverse
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from catalog.forms import ProductForm, ProductVersionFormSet, ProductModeratorsForm
from catalog.models import Product, Version, Category
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.exceptions import PermissionDenied
from django.db.models import Q

from catalog.services import get_categories_from_cache


class ProductListView(ListView):
    model = Product
    extra_context = {
        'title': 'DimStore',
        'slogan': 'DimStore - это лучший вариант для покупки гаджетов'
    }
    paginate_by = 9
    context_object_name = "products"

    def get_context_data(self, *args, object_list=None, **kwargs):
        context_data = super().get_context_data(**kwargs)
        for product in context_data['object_list']:
            active_version = Version.objects.filter(product=product, is_current_version=True).first()
            product.active_version = active_version
        return context_data

    def get_queryset(self):
        user = self.request.user

        # Модератор с правом "can_set_published" видит все продукты
        if user.has_perm('catalog.can_set_published'):
            return Product.objects.all()

        # Владелец видит свои продукты и опубликованные
        elif user.is_authenticated:
            return Product.objects.filter(Q(owner=user) | Q(is_published=True))

        # Обычный пользователь видит только опубликованные продукты
        return Product.objects.filter(is_published=True)


class ProductDetailView(DetailView):
    model = Product
    extra_context = {
        'title': 'DimStore',
        'slogan': 'DimStore - это лучший вариант для покупки гаджетов'
    }
    context_object_name = "product"


class ContactView(TemplateView):
    template_name = 'catalog/contacts.html'
    extra_context = {
        'title': 'Контакты'
    }

    def post(self, request, *args, **kwargs):
        # Обрабатываем POST запрос
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        message = request.POST.get('message')

        # Выводим информацию из post в консоль
        print(f"Пользователь {name} оставил комментарий '{message}'"
              f" и просил связаться с ним по телефону {phone} ")

        # Возвращаем ответ
        context = self.get_context_data()
        return self.render_to_response(context)


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:create_product')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        # ProductFormset = inlineformset_factory(Product, Version, VersionForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = ProductVersionFormSet(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = ProductVersionFormSet(instance=self.object)
        return context_data

    def form_valid(self, form):

        product = form.save()
        user = self.request.user
        product.owner = user
        product.save()

        context_data = self.get_context_data()
        formset = context_data['formset']
        if form.is_valid() and formset.is_valid():
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            return super().form_valid(form)
        else:
            return self.render_to_response(self.get_context_data(form=form, formset=formset))


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm

    def get_success_url(self):
        return reverse('catalog:product_detail', args=[self.kwargs.get('pk')])

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        if self.request.method == 'POST':
            context_data['formset'] = ProductVersionFormSet(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = ProductVersionFormSet(instance=self.object)
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']
        if form.is_valid() and formset.is_valid():
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            return super().form_valid(form)
        else:
            return self.render_to_response(self.get_context_data(form=form, formset=formset))

    def get_form_class(self):
        user = self.request.user
        if user == self.object.owner:
            return ProductForm
        if (user.has_perm('catalog.can_set_published') and user.has_perm('catalog.can_edit_product_description')
                and user.has_perm('catalog.can_edit_category_product')):
            return ProductModeratorsForm
        raise PermissionDenied


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    model = Product
    success_url = reverse_lazy('catalog:product_list')


class CategoryListView(ListView):
    extra_context = {'title': 'Категории товаров', }
    model = Category
    paginate_by = 9
    context_object_name = "category_list"

    def get_queryset(self):
        return get_categories_from_cache()

catalog/templates/catalog/includes/footer.html
{% load catalog_tags %}
<div class="row">
    <div class="col-12 col-md">
        DimStore
        <small class="d-block mb-3 text-muted">&copy; {% current_time %}</small>
    </div>
    <div class="col-6 col-md">
        <h5>О нас</h5>
        <ul class="list-unstyled text-small">
            <li><a class="text-muted" href="{% url 'catalog:contacts'%}">Контакты</a></li>
        </ul>
    </div>
</div>

catalog/templates/catalog/includes/header.html
<header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
    <div class="col-md-3 mb-2 mb-md-0">
        <h5 class="my-0 mr-md-auto font-weight-normal">DimStore</h5>
    </div>

    <div class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
        <nav class="ms-5">
            <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:product_list'%}">Каталог</a>
            <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:category_list'%}">Категории товаров</a>
            <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:contacts'%}">Контакты</a>
            <a class="p-2 btn btn-outline-primary" href="{% url 'blog:articles'%}">Блог</a>
        </nav>
    </div>

    <div class="col-md-3 text-end d-flex">
        {% if user.is_authenticated %}
        <span class="me-3"><b>{{ user.email }}</b></span>
        <a class="btn btn-outline-primary me-2" href="{% url 'users:profile' %}">Профиль</a>
        <form method="post" action="{% url 'users:logout' %}">
            {% csrf_token %}
            <button class="btn btn-outline-primary me-2" type="submit">Выход</button>
        </form>
        {% else %}
        <a class="btn btn-outline-primary me-2" href="{% url 'users:login' %}">Вход</a>
        <a class="btn btn-outline-primary me-2" href="{% url 'users:register' %}">Регистрация</a>
        {% endif %}
    </div>
</header>
    {% include 'catalog/includes/messages.html' %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">{{title}}</h1>
    <p class="lead">{{slogan}}</p>
</div>

catalog/templates/catalog/includes/messages.html
{% if messages %}
<div class="messages position-fixed start-50 translate-middle-x z-3 mt-1 fade show">
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }}">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Закрыть"></button>
    </div>
    {% endfor %}
</div>
{% endif %}

catalog/templates/catalog/includes/paginator.html
{% if page_obj.has_other_pages %}
<nav class="my-5">
    <ul class="pagination">
        <!-- Если существует предыдущая страница
             (если мы не на первой странице)
             рисуем кнопку "Первая страница"... -->
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page=1">Первая</a>
        </li>
        <!-- ...и кнопку "Предыдущая" -->
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                Предыдущая
            </a>
        </li>
        {% endif %}
        <!-- Перебираем в цикле все номера страниц -->
        {% for i in page_obj.paginator.page_range %}
        <!-- Если номер страницы совпадает с i... -->
        {% if page_obj.number == i %}
        <!-- ..."подсвечиваем" кнопку: ставим класс "active"
             и делаем не ссылку, а span (просто текстовый блок) -->
        <li class="page-item active">
            <span class="page-link">{{ i }}</span>
        </li>
        {% else %}
        <!-- Остальные кнопки отрисовываем без подсветки, со ссылками -->
        <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
        </li>
        {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
        <!-- Если существует следующая страница
           (если мы не на последней странице)
           рисуем кнопку "Следующая"... -->
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                Следующая
            </a>
        </li>
        <!-- ...и кнопку "Последняя" -->
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
                Последняя
            </a>
        </li>
        {% endif %}
    </ul>
</nav>
{% endif %}