blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import ArticleListView, ArticleDetailView, ArticleCreateView, ArticleUpdateView, ArticleDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('articles/', ArticleListView.as_view(), name='articles'),
    path('articles/create/', ArticleCreateView.as_view(), name='article_create'),
    path('articles/<slug:slug>/', ArticleDetailView.as_view(), name='article_detail'),
    path('articles/<slug:slug>/edit', ArticleUpdateView.as_view(), name='article_update'),
    path('articles/<slug:slug>/delete', ArticleDeleteView.as_view(), name='article_delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('', include('blog.urls', namespace='blog')),
    path("users/", include("users.urls", namespace="users")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from users.apps import UsersConfig
from users.views import UserCreateView, email_verification, UserPasswordResetView, ProfileView, UserPasswordChangeView

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', UserCreateView.as_view(), name='register'),
    path('email-confirm/<str:token>/', email_verification, name='email-confirm'),
    path("password-reset/", UserPasswordResetView.as_view(), name='password_reset'),
    path("profile/", ProfileView.as_view(), name="profile"),
    path("password-change/", UserPasswordChangeView.as_view(), name='password_change'),
]

users/models.py
from django.apps import apps
from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import AbstractUser
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField

NULLABLE = {"blank": True, "null": True}


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError("The given username must be set")
        email = self.normalize_email(email)
        GlobalUserModel = apps.get_model(
            self.model._meta.app_label, self.model._meta.object_name
        )
        email = GlobalUserModel.normalize_username(email)
        user = self.model(email=email, **extra_fields)
        user.password = make_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")

        return self._create_user(email, password, **extra_fields)


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='Почта', help_text='Введите почту')
    phone = PhoneNumberField(verbose_name='Телефон', **NULLABLE, help_text='Введите номер телефона')
    avatar = models.ImageField(upload_to='users/avatars/', verbose_name='Аватар', **NULLABLE,
                               help_text='Загрузите аватар')
    country = models.CharField(max_length=100, verbose_name='Страна', **NULLABLE, help_text='Введите название страны')
    token = models.CharField(max_length=100, verbose_name='token', **NULLABLE)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"

    def __str__(self):
        return self.email

    objects = UserManager()

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from users.models import User
from django import forms


class UserRegisterForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class UserProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = ("email", "first_name", "last_name", "phone", "avatar", "country",)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields["password"].widget = forms.HiddenInput()

users/views.py
from django.core.mail import send_mail
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView
from users.forms import UserRegisterForm, UserProfileForm
from django.contrib.auth.views import PasswordResetView, PasswordChangeView
from django.contrib.auth.hashers import make_password
from users.models import User
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from config.settings import EMAIL_HOST_USER
import secrets
from users.utils import generate_random_password


class UserCreateView(CreateView):
    model = User
    form_class = UserRegisterForm
    success_url = reverse_lazy("users:login")

    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        token = secrets.token_hex(16)
        user.token = token
        user.save()
        host = self.request.get_host()
        url = f'http://{host}/users/email-confirm/{token}/'
        send_mail(
            subject='Подтверждение почты',
            message=f'Вы оставили заявку на регистрацию на сайте {host}. '
                    f'Перейдите по ссылке для подтверждения почты {url}',
            from_email=EMAIL_HOST_USER,
            recipient_list=[user.email]
        )
        return super().form_valid(form)


def email_verification(request, token):
    user = get_object_or_404(User, token=token)
    user.is_active = True
    user.save()
    return redirect(reverse('users:login'))


class UserPasswordResetView(PasswordResetView):
    """ Контроллер восстановления пароля """
    template_name = "users/password_reset_form.html"
    success_url = reverse_lazy("users:login")

    def form_valid(self, form):
        email = form.cleaned_data['email']
        try:
            user = User.objects.get(email=email)
            new_password = generate_random_password()
            hashed_password = make_password(new_password)
            user.password = hashed_password
            user.save()
            send_mail(
                subject="Восстановление пароля",
                message=f"Ваш новый пароль: {new_password}",
                from_email=EMAIL_HOST_USER,
                recipient_list=[user.email],
            )
            messages.success(self.request, 'Ваш пароль был успешно изменен!')
            return redirect(reverse("users:login"))
        except User.DoesNotExist:
            messages.warning(self.request, 'Пользователя, зарегистрированного с таким email, на сайте нет!')

        return super().form_valid(form)


class ProfileView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy("users:profile")

    def get_object(self, queryset=None):
        return self.request.user


class UserPasswordChangeView(LoginRequiredMixin, PasswordChangeView):
    """ Контроллер изменения пароля """
    template_name = "users/password_change_form.html"
    success_url = reverse_lazy("users:profile")

    def form_valid(self, form):
        messages.success(self.request, 'Ваш пароль был успешно изменен!')
        return super().form_valid(form)

users/templates/users/password_change_form.html
{% extends 'catalog/base.html' %}
{% block content %}
{% load django_bootstrap5 %}
<div class="row">
    <div class="col-12">
        <form method="post" enctype="multipart/form-data">
            <div class="row d-flex justify-content-center">
                <div class="col-6">
                    <div class="card">
                        <div class="card-body">
                            {% csrf_token %}
                            {% bootstrap_form form %}
                            <button type="submit" class="btn btn-success">
                                Поменять пароль
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

users/templates/users/password_reset_form.html
{% extends 'catalog/base.html' %}
{% block content %}
{% load django_bootstrap5 %}
<div class="row">
    <div class="col-12">
        <form method="post" enctype="multipart/form-data">
            <div class="row d-flex justify-content-center">
                <div class="col-6">
                    <div class="card">
                        <div class="card-body">
                            {% csrf_token %}
                            {% bootstrap_form form %}
                            <button type="submit" class="btn btn-success">
                                Создать новый пароль
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'catalog/base.html' %}
{% block content %}
{% load django_bootstrap5 %}
<div class="row d-flex justify-content-center">
    <div class="col-6">
        {% if user.is_authenticated %}
        <h1 class="mt-1 text-center">Профиль пользователя</h1>
        {% else %}
        <h1 class="mt-1 text-center">Регистрация</h1>
        {% endif %}
    </div>
</div>
<div class="row">
    <div class="col-12">
        <form method="post" enctype="multipart/form-data">
            <div class="row d-flex justify-content-center">
                <div class="col-6">
                    <div class="card">
                        <div class="card-body">
                            {% csrf_token %}
                            {% bootstrap_form form %}
                            {% if user.is_authenticated %}
                            <button type="submit" class="btn btn-success">
                                Сохранить изменения
                            </button>
                            <a href="{% url 'users:password_change' %}" class="btn btn-link">Изменить пароль</a>
                            {% else %}
                            <button type="submit" class="btn btn-success">
                                Зарегистрироваться
                            </button>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}