blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import ArticleListView, ArticleDetailView, ArticleCreateView, ArticleUpdateView, ArticleDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('articles/', ArticleListView.as_view(), name='articles'),
    path('articles/create/', ArticleCreateView.as_view(), name='article_create'),
    path('articles/<slug:slug>/', ArticleDetailView.as_view(), name='article_detail'),
    path('articles/<slug:slug>/edit', ArticleUpdateView.as_view(), name='article_update'),
    path('articles/<slug:slug>/delete', ArticleDeleteView.as_view(), name='article_delete'),
]

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from catalog.apps import CatalogConfig
from catalog.views import ContactView, ProductListView, ProductDetailView, ProductCreateView, ProductUpdateView, \
    ProductDeleteView, CategoryListView

app_name = CatalogConfig.name

urlpatterns = [
    path('', ProductListView.as_view(), name='product_list'),
    path('products/<int:pk>/', cache_page(60)(ProductDetailView.as_view()), name='product_detail'),
    path('products/create/', ProductCreateView.as_view(), name='create_product'),
    path('products/<int:pk>/edit', ProductUpdateView.as_view(), name='product_update'),
    path('products/<int:pk>/delete', ProductDeleteView.as_view(), name='product_delete'),
    path('categories/', CategoryListView.as_view(), name='category_list'),
    path('contacts/', ContactView.as_view(), name='contacts')
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('', include('blog.urls', namespace='blog')),
    path("users/", include("users.urls", namespace="users")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models

from users.models import User

NULLABLE = {"blank": True, "null": True}


class Category(models.Model):
    """
    Класс категории товара
    """

    name = models.CharField(
        max_length=100,
        verbose_name="Наименование",
        help_text="Введите наименование категории",
    )

    description = models.TextField(
        verbose_name="Описание",
        help_text="Введите описание категории",
        **NULLABLE,
    )

    class Meta:
        verbose_name = "категория"
        verbose_name_plural = "категории"
        ordering = ("name",)

    def __str__(self):
        """
        Строковое категории
        """
        return f"{self.name}"


class Product(models.Model):
    """
    Класс товара
    """

    name = models.CharField(
        max_length=100,
        verbose_name="Товар",
        help_text="Введите наименование товара",
    )

    description = models.TextField(
        verbose_name="Описание",
        help_text="Введите описание товара",
        **NULLABLE,
    )

    preview = models.ImageField(
        upload_to="catalog/preview",
        verbose_name="Изображение",
        help_text="Загрузите изображение товара",
        **NULLABLE,
    )

    category = models.ForeignKey(
        "Category",
        on_delete=models.SET_NULL,
        verbose_name="Категория",
        help_text="Введите категорию товара",
        related_name="products",
        **NULLABLE,
    )

    price = models.DecimalField(
        max_digits=12,
        decimal_places=2,
        verbose_name="Цена",
        help_text="Введите цену",
        default=0.0,
    )

    owner = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        verbose_name="Владелец",
        help_text="Укажите владельца",
        **NULLABLE,
    )

    is_published = models.BooleanField(
        default=False,
        verbose_name="Опубликовано",
        help_text="Отметить для публикации"
    )

    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    updated_at = models.DateTimeField(
        auto_now=True, verbose_name="Дата последнего изменения"
    )

    class Meta:
        verbose_name = "товар"
        verbose_name_plural = "товары"
        ordering = (
            "name",
            "price",
            "created_at",
            "updated_at",
            "category",
        )
        permissions = [
            ('can_set_published', 'Can set published'),
            ('can_edit_product_description', 'Can edit description'),
            ('can_edit_category_product', 'Can edit category',),
        ]

    def __str__(self):
        return f"{self.name}"


class Contact(models.Model):
    name = models.CharField(max_length=100, verbose_name="Имя")
    phone = models.CharField(max_length=12, verbose_name="Телефон")
    address = models.CharField(max_length=255, verbose_name="Адрес", **NULLABLE)

    class Meta:
        verbose_name = "контакт"
        verbose_name_plural = "контакты"
        ordering = ("name",)

    def __str__(self):
        return self.name


class Version(models.Model):
    product = models.ForeignKey(
        Product,
        on_delete=models.SET_NULL,
        verbose_name="Продукт",
        **NULLABLE,
        related_name="version",
    )
    version_number = models.IntegerField(verbose_name="Номер версии")
    name = models.CharField(max_length=150, verbose_name="Название версии")
    is_current_version = models.BooleanField(
        default=False, verbose_name="Признак текущей версии"
    )

    class Meta:
        verbose_name = "Версия"
        verbose_name_plural = "Версии"
        ordering = (
            "product",
            "version_number",
            "name",
        )

    def __str__(self):
        return f"{self.name}"

catalog/forms.py
from django import forms
from .models import Product, Version


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        exclude = ("owner",)

    prohibited_words_list = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция',
                             'радар']

    def clean_name(self):
        cleaned_data = self.cleaned_data['name']

        for word in self.prohibited_words_list:
            if word in cleaned_data:
                raise forms.ValidationError('Запрещенные слова в названии!')

        return cleaned_data

    def clean_description(self):
        cleaned_data = self.cleaned_data['description']

        for word in self.prohibited_words_list:
            if word in cleaned_data:
                raise forms.ValidationError('Запрещенные слова в описании!')

        return cleaned_data


class ProductModeratorsForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = ('description', 'category', 'is_published',)


class VersionForm(forms.ModelForm):
    class Meta:
        model = Version
        fields = "__all__"


ProductFormset = forms.inlineformset_factory(
    Product,
    Version,
    form=VersionForm,
    extra=1)


class ProductVersionFormSet(ProductFormset):
    def clean(self):
        version_forms = self.forms
        is_latest_count = len([1 for f in version_forms if f.instance.is_current_version])
        if is_latest_count > 1:
            raise forms.ValidationError('Может быть только одна текущая версия продукта!')
        super().clean()

catalog/views.py
from django.urls import reverse_lazy, reverse
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from catalog.forms import ProductForm, ProductVersionFormSet, ProductModeratorsForm
from catalog.models import Product, Version, Category
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.exceptions import PermissionDenied
from django.db.models import Q

from catalog.services import get_categories_from_cache


class ProductListView(ListView):
    model = Product
    extra_context = {
        'title': 'DimStore',
        'slogan': 'DimStore - это лучший вариант для покупки гаджетов'
    }
    paginate_by = 9
    context_object_name = "products"

    def get_context_data(self, *args, object_list=None, **kwargs):
        context_data = super().get_context_data(**kwargs)
        for product in context_data['object_list']:
            active_version = Version.objects.filter(product=product, is_current_version=True).first()
            product.active_version = active_version
        return context_data

    def get_queryset(self):
        user = self.request.user

        # Модератор с правом "can_set_published" видит все продукты
        if user.has_perm('catalog.can_set_published'):
            return Product.objects.all()

        # Владелец видит свои продукты и опубликованные
        elif user.is_authenticated:
            return Product.objects.filter(Q(owner=user) | Q(is_published=True))

        # Обычный пользователь видит только опубликованные продукты
        return Product.objects.filter(is_published=True)


class ProductDetailView(DetailView):
    model = Product
    extra_context = {
        'title': 'DimStore',
        'slogan': 'DimStore - это лучший вариант для покупки гаджетов'
    }
    context_object_name = "product"


class ContactView(TemplateView):
    template_name = 'catalog/contacts.html'
    extra_context = {
        'title': 'Контакты'
    }

    def post(self, request, *args, **kwargs):
        # Обрабатываем POST запрос
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        message = request.POST.get('message')

        # Выводим информацию из post в консоль
        print(f"Пользователь {name} оставил комментарий '{message}'"
              f" и просил связаться с ним по телефону {phone} ")

        # Возвращаем ответ
        context = self.get_context_data()
        return self.render_to_response(context)


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:create_product')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        # ProductFormset = inlineformset_factory(Product, Version, VersionForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = ProductVersionFormSet(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = ProductVersionFormSet(instance=self.object)
        return context_data

    def form_valid(self, form):

        product = form.save()
        user = self.request.user
        product.owner = user
        product.save()

        context_data = self.get_context_data()
        formset = context_data['formset']
        if form.is_valid() and formset.is_valid():
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            return super().form_valid(form)
        else:
            return self.render_to_response(self.get_context_data(form=form, formset=formset))


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm

    def get_success_url(self):
        return reverse('catalog:product_detail', args=[self.kwargs.get('pk')])

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        if self.request.method == 'POST':
            context_data['formset'] = ProductVersionFormSet(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = ProductVersionFormSet(instance=self.object)
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']
        if form.is_valid() and formset.is_valid():
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            return super().form_valid(form)
        else:
            return self.render_to_response(self.get_context_data(form=form, formset=formset))

    def get_form_class(self):
        user = self.request.user
        if user == self.object.owner:
            return ProductForm
        if (user.has_perm('catalog.can_set_published') and user.has_perm('catalog.can_edit_product_description')
                and user.has_perm('catalog.can_edit_category_product')):
            return ProductModeratorsForm
        raise PermissionDenied


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    model = Product
    success_url = reverse_lazy('catalog:product_list')


class CategoryListView(ListView):
    extra_context = {'title': 'Категории товаров', }
    model = Category
    paginate_by = 9
    context_object_name = "category_list"

    def get_queryset(self):
        return get_categories_from_cache()

catalog/templates/catalog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{title}}</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    {% load django_bootstrap5 %}
    {% bootstrap_css %}
</head>
<body>
<div class="container">
    {% include 'catalog/includes/header.html' %}
</div>
<div class="container">
    {% block content %}
    {% endblock %}

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        {% include 'catalog/includes/footer.html' %}
    </footer>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
<script src="{% static 'js/hide_messages.js' %}"></script>
</body>
</html>

catalog/templates/catalog/category_list.html
{% extends 'catalog/base.html' %}
{% load catalog_tags %}
{% block content %}
<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3 mb-3">
    {% for category in category_list %}
    <div class="col">
        <div class="card-body">
            <h4 class="product-title text-bold my-3">{{ category.name }}</h4>
            <p class="card-text description product-details">{{ category.description }}</p>
        </div>
    </div>
    {% endfor %}
</div>
{% include "catalog/includes/paginator.html" %}
{% endblock %}

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="row text-start">
    <div class="col-lg-9 col-md-6 col-sm-12">
        <div class="card mb-4 box-shadow">
            <div class="card-body">
                <table class="table table-striped">
                    <tr>
                        <td class="w-25">Страна</td>
                        <td>Россия</td>
                    </tr>
                    <tr>
                        <td class="w-25">ИНН</td>
                        <td>12-34567890</td>
                    </tr>
                    <tr>
                        <td class="w-25">Адрес</td>
                        <td>Московская область, г. Одинцово</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
    <div class="col-lg-3 col-md-6 col-sm-12">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
            </div>
            <div class="card-body">
                <form method="post" action="" class="form-floating">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="name">Имя</label>
                        <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                    </div>
                    <div class="mb-3">
                        <label for="phone">Телефон</label>
                        <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон"
                               required>
                    </div>
                    <div class="mb-3">
                        <label for="message">Сообщение</label>
                        <textarea type="text" name="message" class="form-control" id="message"
                                  placeholder="Ваше сообщение" required></textarea>
                    </div>
                    <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="position-relative w-100 vh-100">
    <form method="post" class="position-absolute top-50 start-50 translate-middle ">
        {% csrf_token %}
        <p>Вы действительно хотите удалить товар <b>{{ object.name }}</b>?</p>
        <div class="btn-group justify-content-center w-100" role="group">
            <a href="{% url 'catalog:product_detail' object.pk %}" class="btn btn-success">Отмена</a>
            <button class="btn btn-danger" type="submit">Удалить</button>
        </div>
    </form>
</div>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% load catalog_tags %}
{% block content %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb text-bold">
        <li class="breadcrumb-item" aria-current="page"><a href="{% url 'catalog:product_list' %}">В каталог</a></li>
    </ol>
</nav>
<div class="row">
    <div class="col-md-5">
        <div class="main-img">
            <img class="img-fluid" src="{{ product.preview | media_filter }}"
                 alt="Product">
        </div>
    </div>
    <div class="col-md-7">
        <div class="main-description px-2">
            <div class="category text-bold">
                Категория: {{ product.category }}
            </div>
            <div class="product-title text-bold my-3">
                {{ product.name }}
            </div>

            <div class="price-area my-4">
                <p class="new-price text-bold mb-1">{{ product.price }} ₽</p>
            </div>

            <div class="buttons d-flex my-5">
                <div class="block">
                    <button class="shadow btn custom-btn">В корзину</button>
                </div>

                <div class="block quantity">
                    <input type="number" class="form-control" id="cart_quantity" value="1" min="0" max="5"
                           placeholder="Enter email" name="cart_quantity">
                </div>
            </div>
        </div>

        <div class="product-details my-4">
            <p class="details-title text-color mb-1">Описание</p>
            <p class="description">{{ product.description }}</p>
        </div>
    </div>
    {% if user.is_authenticated %}
    <div class="mt-4 btn-group" role="group">
        {% if perms.catalog.can_set_published and perms.catalog.can_edit_product_description and perms.catalog.can_edit_category_product or user == product.owner %}
        <a href="{% url 'catalog:product_update' product.pk %}" class="btn btn-primary m-1">Изменить продукт</a>
        {% endif %}
        {% if user.is_superuser or user == product.owner %}
        <a href="{% url 'catalog:product_delete' product.pk %}" class="btn btn-danger m-1">Удалить продукт</a>
        {% endif %}
    </div>
    {% endif %}
    <div class="mt-4 btn-group" role="group">
        {% if perms.catalog.can_set_published or product.owner == user %}
            {% if product.is_published %}
            <span class="badge bg-success">Опубликован пользователем {{ product.owner }}</span>
            {% else %}
            <span class="badge bg-danger">Не опубликован, пользователь: {{ product.owner }}</span>
            {% endif %}
        {% endif %}
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}
{% block content %}
{% load django_bootstrap5 %}
<div class="row d-flex justify-content-center">
    <div class="col-6">
        {% if object %}
        <h1 class="mt-1">Изменить товар</h1>
        {% else %}
        <h1 class="mt-1">Создать новый товар</h1>
        {% endif %}
    </div>
</div>
<!-- Форма создания и изменения товара -->

<div class="col-12">
    <form method="post" enctype="multipart/form-data">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        {% csrf_token %}
                        {% bootstrap_form form %}
                        <button type="submit" class="btn btn-primary">
                            {% if object %}
                            Сохранить изменения
                            {% else %}
                            Добавить товар
                            {% endif %}
                        </button>
                    </div>
                </div>
            </div>
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        {{ formset.management_form }}
                        {% bootstrap_formset_errors formset layout='inline' %}
                        {% for form in formset.forms %}
                            {% bootstrap_form form %}
                            {% if not forloop.last %}
                                <hr>
                            {% endif %}
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}
{% load catalog_tags %}
{% block content %}
{% if user.is_authenticated %}
<div class="row">
    <div class="col-4 d-flex justify-content-center">
        <a class="p-2 btn btn-outline-primary mb-3" href="{% url 'catalog:create_product' %}">Добавить товар</a>
    </div>
</div>
{% endif %}

<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3 mb-3">
    {% for product in products %}
    <div class="col">
        <a class="image" href="{% url 'catalog:product_detail' product.pk %}">
            <img src="{{ product.preview | media_filter }}"
                 class="card-img-top"
                 alt="Product">
        </a>

        <div class="card-body">
            <a class="btn" href="{% url 'catalog:product_detail' product.pk %}">
                <h4 class="product-title text-bold my-3">{{ product.name }}</h4>
            </a>
            <p class="card-text description product-details">{{ product.description | truncatechars:100 }}</p>
            <div class="d-flex justify-content-between align-items-center">
                <div class="pricing-card-title text-bold">{{ product.price }} ₽</div>
                {% if product.active_version %}
                <span class="badge text-bg-info">{{product.active_version.name}}</span>
                {% endif %}
            </div>
        </div>
        <div class="card-footer">
            {% if perms.catalog.can_set_published or product.owner == user %}
                {% if product.is_published %}
                <span class="badge bg-success">Опубликован пользователем {{ product.owner }}</span>
                {% else %}
                <span class="badge bg-danger">Не опубликован, пользователь: {{ product.owner }}</span>
                {% endif %}
            {% endif %}
        </div>
    </div>
    {% endfor %}
    {% if not products %}
    <p>Нет доступных продуктов</p>
    {% endif %}

</div>
{% include "catalog/includes/paginator.html" %}
{% endblock %}